from deep_mimic.gym_env.deep_mimic_env import HumanoidDeepMimicBackflipBulletEnv, HumanoidDeepMimicWalkBulletEnv
from deep_mimic.gym_env.deep_mimic_env_selector import HumanoidDeepMimicWalkerBulletEnv, HumanoidDeepMimicDancerBulletEnv, HumanoidDeepMimicSignerBulletEnv
from deep_mimic.gym_env.deep_mimic_env_upper import HumanoidDeepMimicUpperSignerBulletEnv
from deep_mimic.gym_env.deep_mimic_env_hand import HandDeepMimicSignerBulletEnv
from deep_mimic.gym_env.deep_mimic_env_whole import WholeDeepMimicSignerBulletEnv